#! /bin/bash

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in

    wgb-host)
        echo "FAIBASE DHCPC UBUNTU_16";;

    docker)
	echo "FAIBASE DHCPC UBUNTU_16 DOCKER" ;;

    *)
	exit 1 ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB_PC
exit 0

